== Kubernetes

Deploy a Kubernetes cluster on libvirt using Terraform.

=== Requirements

* Libvirt (tested with 5.6.0 version).
* Terraform (tested with 0.12.24 version).
* Libvirt provider for Terraform (tested with 0.6.2 version).

Install requirements.

[source,bash]
----
make require
----

=== Setup Libvirt

Use `+virsh+` command utility to configure libvirt.

[source,bash]
----
export LIBVIRT_DEFAULT_URI="qemu:///system"
----

Check if libvirt is running.

[source,bash]
----
virsh version --daemon
----

==== QEMU permissions

The provider does not currently support to create volumes with different mode than `+root:root+` so QEMU agent must run as priviledged.

[source,bash]
----
sed -i '/^#user/s/^#//' /etc/libvirt/qemu.conf
sed -i '/^#group/s/^#//' /etc/libvirt/qemu.conf
----

Restart libvirt daemon.

[source,bash]
----
systemctl restart libvirtd
----

== Deploy Kubernetes cluster

Deploy Kubernetes cluster using Terraform.

[source,bash]
----
make
----

Configure `+kube-admin+` user credentials.

[source,bash]
----
export KUBECONFIG="src/kubeconfig/kubeconfig-kube-admin.yml"
----

Wait until the workers are up and running.

[source,bash]
----
kubectl get nodes
----

=== DNS

Deploy Kubernetes internal DNS.

[source,bash]
----
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm install coredns --values=src/dns/coredns/values.yaml --namespace=kube-system stable/coredns
----

==== Testing

Create an example job in `+kubernetes-dns-testing+` namespace to query CoreDNS server.

[source,bash]
----
kubectl apply -f testing/dns
----

Verify internal DNS resolution.

[source,bash]
----
kubectl logs -l job-name=coredns -n kubernetes-dns-testing
----

Verify internet DNS resolution.

[source,bash]
----
kubectl logs -l job-name=internet -n kubernetes-dns-testing
----

== Destroy Kubernetes cluster

Destroy Kubernetes cluster using Terraform.

```
make clean
```

== Troubleshooting

=== Terraform

Enable debug mode by setting `+TF_VAR_DEBUG+` to `+true+` before planning terraform changes.

[source,bash]
----
export TF_VAR_DEBUG="true"
----

=== ETCD

Connect to a master node and run `+etcdctl+` tool to check etcd status.

[source,bash]
----
export ETCDCTL_CACERT="/var/lib/etcd/certificates/etcd-root-ca.pem"
export ETCDCTL_CERT="/var/lib/etcd/certificates/etcd-member.pem"
export ETCDCTL_KEY="/var/lib/etcd/certificates/etcd-member.key"

etcdctl member list -w table
etcdctl endpoint status --cluster=true -w table
----

== References

* https://github.com/kelseyhightower/kubernetes-the-hard-way
* https://www.altoros.com/blog/kubernetes-networking-writing-your-own-simple-cni-plug-in-with-bash/
* https://medium.com/faun/kubernetes-without-kube-proxy-1c5d25786e18
