apiVersion: batch/v1
kind: Job
metadata:
  name: coredns
  namespace: kubernetes-dns-testing
  labels:
    component: test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: shell
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command: [ "/bin/sh" ]
          args:
            - -c
            - dig -t A +short kubernetes.default.svc.cluster.local
          securityContext:
            capabilities:
              add:
                - NET_RAW
